# Kubernetes Cluster
# k3sm-ss1.loyaltyplus.aero
# k3sm-ssw10.loyaltyplus.aero
# k3sm-ssw11.loyaltyplus.aero
# k3sm-ssw12.loyaltyplus.aero
#
# k3sm-ss2.loyaltyplus.aero
# k3sm-ssw20.loyaltyplus.aero
#
# k3sm-ss3.loyaltyplus.aero
---
primaryNode:  
  nickname: Primary Master Node
  ipAddress: 10.154.2.40
  fqdn: k3sm-ss1.loyaltyplus.aero
  userId: nickm
  script: Primary-Master-Node-ip-89.sh 
  k3sToken: K10d80e2607d2b372531758ff421af503d06c02c1992f41ce09cc57db40f45c0f5f::server:c65119161dbfdabefde333a2ce02744a

otherMasterNodes:
- nickname: Second Master Node
  ipAddress: 10.154.2.50
  fqdn: buffalo.loseyourip.com
  userId: nickm
  script: Second-Master-Node-ip-88.sh

- nickname: Third Master Node
  ipAddress: 10.154.2.60
  fqdn: k3sm-ss3.loyaltyplus.aero
  userId: nickm
  script: Third-Master-Node-ip-4.sh

workernodes:
- nickname: First Worker Node
  ipAddress: 10.154.2.41
  fqdn: k3sm-ssw10.loyaltyplus.aero
  userId: nickm
  script: First-Worker-Node-ip-93.sh 
 
- nickname: Second Worker Node
  ipAddress: 10.154.2.42
  fqdn: k3sm-ssw11.loyaltyplus.aero
  userId: nickm
  script: Second-Worker-Node-ip-95.sh

- nickname: Third Worker Node
  ipAddress: 10.154.2.43
  fqdn: k3sm-ssw12.loyaltyplus.aero
  userId: nickm
  script: Third-Worker-Node-ip-97.sh

- nickname: Fourth Worker Node
  ipAddress: 10.154.2.51
  fqdn: k3sm-ssw20.loyaltyplus.aero
  userId: nickm
  script: Fourth-Worker-Node-ip-188.sh

targetFile: K3S_Auto_Cluster_Generator_Schedule.txt
