# create_k3s_worker_node.yml
- name: Create Worker Node
  hosts: localhost
  gather_facts: false
  vars:
    node_name: "{{ node_name }}"
    master_node_ip_address: "{{ master_node_ip_address }}"
    k3s_token: "{{ k3s_token }}"  # Set your K3S token here
    dest_file: "/opt/k3s/{{ destination_file }}"
  tasks:
    - name: Execute k3s_node_maker.j2 template for WORKER_NODE
      template:
        src: ../templates/k3s_node_maker.j2
        dest: "{{ dest_file }}"
      vars:
        node_type: "WORKER_NODE"
        node_name: "{{ node_name }}"
        master_node_ip_address: "{{ master_node_ip_address }}"
        k3s_token: "{{ k3s_token }}"

    - name: Change file permissions of other_master_node.sh
      become: true  # This will escalate privileges if required
      file:
        path: "{{ dest_file }}"
        mode: "775"

    - name: Change file permissions of other_master_node.sh
      become: true
      file:
        path: "{{ dest_file }}"
        mode: "775"
        owner: "{{ username }}"  # Set the owner here
        group: "{{ username }}"  # Set the group here

    - name: Copy file to remote host using SCP
      ansible.builtin.command: >
        sshpass -p "{{ password }}"
        scp -o StrictHostKeyChecking=no -p "/opt/k3s/1st_master_node.sh"
        "{{ username  }}@{{ master_node_ip_address}}:/opt/k3s"
      delegate_to: localhost

