- name: Create Primary Master Node
  hosts: localhost
  gather_facts: false
  vars:
    node_name: "{{ node_name }}"
    master_node_ip_address: "{{ master_node_ip_address }}"
    dest_file: "/opt/k3s/{{ destination_file }}"
  tasks:
    - name: Execute k3s_node_maker.j2 template for 1ST_MASTER_NODE
      template:
        src: ../templates/k3s_node_maker.j2
        dest: "{{ dest_file }}"
      vars:
        node_type: "{{ node_type }}"
        node_name: "{{ node_name }}"
        master_node_ip_address: "{{ master_node_ip_address }}"

    - name: Change file permissions of other_master_node.sh
      become: true  # This will escalate privileges if required
      file:
        path: "{{ dest_file }}"
        mode: "775"
   
    - name: Fetch 1st_master_node.sh from Semaphore server
      fetch:
        src: "/opt/k3s/1st_master_node.sh"
        dest: "/opt/k3s/1st_master_node.sh"
        flat: yes
      delegate_to: leopard.loseyourip.com
