- name: Create Primary Master Node
  hosts: localhost
  gather_facts: false
  vars:
    node_name: "tiger.loseyourip.com"
    master_node_ip_address: "10.154.2.91"
  tasks:
    - name: Execute k3s_node_maker.j2 template for 1ST_MASTER_NODE
      template:
        src: k3s_node_maker.j2
        dest: /path/to/output/1st_master_node.sh
      vars:
        node_type: "1ST_MASTER_NODE"
        node_name: "{{ node_name }}"
        master_node_ip_address: "{{ master_node_ip_address }}"

