- name: Create Primary Master Node
  hosts: localhost
  gather_facts: false
  vars:
    node_name: "{{ node_name }}"
    master_node_ip_address: "{{ master_node_ip_address }}"
    dest_file: "/opt/k3s/{{ destination_file }}"
    scp_script_path: "/opt/k3s/{{ scp_file }}"
    username: "{{ username }}"  # Define the username variable here
  tasks:
    - name: 1. Execute k3s_node_maker.j2 template for 1ST_MASTER_NODE - {{ dest_file }}
      template:
        src: ../templates/k3s_node_maker.j2
        dest: "{{ dest_file }}"
      vars:
        node_type: "{{ node_type }}"
        node_name: "{{ node_name }}"
        master_node_ip_address: "{{ master_node_ip_address }}"
      become: true  # If escalated permissions are needed

    - name: 2. Change file permissions of other_master_node.sh - {{ dest_file }}
      become: true
      file:
        path: "{{ dest_file }}"
        mode: "775"
        owner: "{{ username }}"  # Set the owner here
        group: "{{ username }}"  # Set the group here

    - name: 3. SCP Copy file  {{ dest_file }} to {{ master_node_ip_address}}
      ansible.builtin.command: >
        sshpass -p "{{ password }}"
        scp -o StrictHostKeyChecking=no -p "/{{ dest_file }}"
        "{{ username  }}@{{ master_node_ip_address}}:/home/{{ username  }}"
      delegate_to: localhost
