# create_k3s_other_master_node.yml
- name: Create Other Master Node
  hosts: localhost
  gather_facts: false
  vars:
    node_name: "{{ node_name }}"
    master_node_ip_address: "{{ master_node_ip_address }}"
    k3s_token: "{{ k3s_token }}"  # Set your K3S token here
    dest_file: "/opt/k3s/{{ destination_file }}"
  tasks:
    - name: 1. Execute k3s_node_maker.j2 template for OTHER_MASTER_NODE - {{ dest_file }}
      template:
        src: ../templates/k3s_node_maker.j2
        dest: "{{ dest_file }}"
      vars:
        node_type: "{{ node_type }}"
        node_name: "{{ node_name }}"
        node_ip: "{{node_ip}}"
        master_node_ip_address: "{{ master_node_ip_address }}"
        k3s_token: "{{ k3s_token }}"

    - name: 2. Change file permissions of other_master_node.sh - {{ dest_file }}
      become: true
      file:
        path: "{{ dest_file }}"
        mode: "775"
        owner: "{{ username }}"  # Set the owner here
        group: "{{ username }}"  # Set the group here

    - name: 3. SCP Copy file to {{ node_ip}} - {{ dest_file }}
      ansible.builtin.command: >
        sshpass -p "{{ password }}"
        scp -o StrictHostKeyChecking=no -p "/opt/k3s/1st_master_node.sh"
        "{{ username  }}@{{ node_ip}}:/home/{{ username  }}"
      delegate_to: localhost
