---
- name: Run K3s Primary Master Node Script
  hosts: "{{ node_name }}"
  gather_facts: false
  tasks:
    - name: Create /opt/k3s folder if it doesn't exist
      file:
        path: "/opt/k3s"
        state: directory
      delegate_to: localhost

    - name: Copy 1st_master_node.sh to the server
      copy:
        src: "/opt/k3s/1st_master_node.sh"
        dest: "/opt/k3s/1st_master_node.sh"

#    - name: Run the shell script on the server
#      shell: "/opt/k3s/1st_master_node.sh"
#      args:
#        chdir: "/opt/k3s"
#      delegate_to: localhost


