# playbooks/run_other_master.yml

- name: Create Other Master Node
  hosts: giraffe.kozow.com
  gather_facts: false

  vars_files:
    - user_credentials.yml

  tasks:
    - name: Execute command as root using sudo
      command: whoami
      become: true
      become_user: nickm
