# playbooks/run_other_master.yml

- name: Create Other Master NodeS
  hosts: other_master_nodes
  gather_facts: false

  tasks:
    - name: Execute command as nickm using sudo
      command: whoami
      become: true
      become_user: nickm
