# playbooks/run_other_master.yml

# Please dont use this I have not got it working
- name: Your Ansible Playbook
  hosts: other_master_nodes
  become: true


  tasks:

    - name: APT Package Updater
      apt:
        upgrade: yes
        update_cache: yes
