# run_k3s_primary_master_node_script.yml
---
- name: Run K3s Primary Master Node Script
  hosts: "{{ master_node_ip_address }}"
  gather_facts: false
  tasks:
    - name: Run the script on the server
      ansible.builtin.shell:
        cmd: "/home/{{ username }}/{{ node_name }}.sh"
      args:
        stdout_callback: oneline





