# playbooks/run_other_master.yml

# Please dont use this I have not got it working

---
- hosts: all_active_nodes

  become: true

  tasks:
    - name: APT Package Updater
      apt:
        upgrade: yes
        update_cache: yes
