- name: Create Other Master Node
  hosts: "{{ node_name }}"
  gather_facts: false
  vars:
    node_name: "{{ node_name }}"
    master_node_ip_address: "{{ master_node_ip_address }}"
    dest_file: "{{ destination_file }}"
    destination_folder: "/opt/k3s/"
    node_ip: "{{ node_ip }}"
    username: "{{ username }}"
    password: "{{ password }}"

  tasks:
    - name: Execute command as specific user with password
      expect:
        command: whoami
        responses:
          Password: "P@55w0rd"
      become: true
      become_user: "nickm"
