- name: Create Other Master Node
  hosts: "{{ node_name }}"
  gather_facts: false
  vars:
    node_name: "{{ node_name }}"
    master_node_ip_address: "{{ master_node_ip_address }}"
    k3s_token: "{{ k3s_token }}"  # Set your K3S token here
    dest_file: "{{ destination_file }}"
    destination_folder: "/opt/k3s/" #"/home/{{username}}/" #"/opt/k3s/}"
    node_ip: "{{node_ip}}"

  tasks:

    - name: Create more variables
      set_fact:
        source_file: "/opt/k3s/{{ dest_file }}"
        username:  "{{ username }}"

    - name: check user
      remote_user: username
      shell: whoami
